// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAD5oqYXuqDeWU5mWxMFGVzrnLCiYfTvc0',
    appId: '1:810629838655:web:29f9fbe2189b9cae03c58a',
    messagingSenderId: '810629838655',
    projectId: 'freshlinkmad20251-g43',
    authDomain: 'freshlinkmad20251-g43.firebaseapp.com',
    storageBucket: 'freshlinkmad20251-g43.firebasestorage.app',
    measurementId: 'G-TBJCWMBRJJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4PvhVNaXUX2jCYMSypVIKcvrgGrbNjnI',
    appId: '1:810629838655:android:439fd539c388ad8403c58a',
    messagingSenderId: '810629838655',
    projectId: 'freshlinkmad20251-g43',
    storageBucket: 'freshlinkmad20251-g43.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRaHmrEo37pPsTNk56pzqR7WpTEmcADuA',
    appId: '1:810629838655:ios:7a900381f5400a7403c58a',
    messagingSenderId: '810629838655',
    projectId: 'freshlinkmad20251-g43',
    storageBucket: 'freshlinkmad20251-g43.firebasestorage.app',
    androidClientId: '810629838655-pkb9otnukf5c0nntmgepu89f6ifseh0i.apps.googleusercontent.com',
    iosClientId: '810629838655-c01eisafcvn77ti75r6fttb12oat1v0m.apps.googleusercontent.com',
    iosBundleId: 'com.example.firstApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRaHmrEo37pPsTNk56pzqR7WpTEmcADuA',
    appId: '1:810629838655:ios:7a900381f5400a7403c58a',
    messagingSenderId: '810629838655',
    projectId: 'freshlinkmad20251-g43',
    storageBucket: 'freshlinkmad20251-g43.firebasestorage.app',
    androidClientId: '810629838655-pkb9otnukf5c0nntmgepu89f6ifseh0i.apps.googleusercontent.com',
    iosClientId: '810629838655-c01eisafcvn77ti75r6fttb12oat1v0m.apps.googleusercontent.com',
    iosBundleId: 'com.example.firstApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAD5oqYXuqDeWU5mWxMFGVzrnLCiYfTvc0',
    appId: '1:810629838655:web:e80fd9e2b8e8b2b203c58a',
    messagingSenderId: '810629838655',
    projectId: 'freshlinkmad20251-g43',
    authDomain: 'freshlinkmad20251-g43.firebaseapp.com',
    storageBucket: 'freshlinkmad20251-g43.firebasestorage.app',
    measurementId: 'G-ZDE6HWFDW6',
  );

}